name: Tests

on:
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Initialize Airflow DB
        run: uv run --group test airflow db migrate
        env:
          AIRFLOW__CORE__UNIT_TEST_MODE: "True"

      - name: Run tests
        run: |
          PG_CTL=$(find /usr/lib/postgresql -name pg_ctl | sort -V | tail -1)
          uv run --group test pytest --postgresql-exec="$PG_CTL"
        env:
          AIRFLOW__CORE__UNIT_TEST_MODE: "True"
